services:
  node:
    image: "node:20"
    user: "node"
    working_dir: /home/node/app
    networks:
      traefik:
    environment:
      NODE_ENV: production
      PORT: 3000 # Change it if you'd like; be sure to change it down below as well though
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:$$PORT/ping"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
    volumes:
      - ./:/home/node/app
    expose:
      - "3000"
    ports: # use if it is necessary to expose the container to the host machine
      - "3000:3000"
    command: "npm start"
